#!/usr/bin/env python

def build(bld):
    import Common
    obj_rep = bld.create_obj('subst')
    obj_rep.source = 'org.freedesktop.Telepathy.ConnectionManager.mixer.service.in'
    obj_rep.target = 'org.freedesktop.Telepathy.ConnectionManager.mixer.service'

    Common.install_files('DATADIR', 'telepathy/managers/', 'mixer.manager')
    Common.install_files('DATADIR', 'dbus-1/services/',
            'org.freedesktop.Telepathy.ConnectionManager.mixer.service')
    Common.install_files('DATADIR', 'empathy/icons/hicolor/scalable/apps/', 'im-mxit.svg')
    Common.install_files('DATADIR', 'empathy/icons/', 'empathy-account-widget-mxit.glade')
    Common.install_files('DATADIR', 'mission-control/profiles/', 'mxit.profile')

